module.exports = {
  UNIT_MEASURES: ['G', 'UN'],
  SALE_STATES: ['TODO', 'WIP', 'DONE_PICK_UP', 'DONE_DELIVERY', 'FINISHED'],
  DELIVERY_TYPE: ['PICK_UP', 'DELIVERY'],
  PAYMENT_METHOD: ['CASH', 'TRANSFER'],
  PRODUCT_STATUS_TYPES: {
    DISABLED: 'DISABLED',
    ENABLED: 'ENABLED',
  },
  EXTRA_PREPARATION_TIME_MINUTE_PERCENTAGE: 0.15,
  RECIPE_QUANTITY_STOCK_PERCENTAGE_CALCULATION: 5,
};
